spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

  flyway:
    enabled: true

  datasource:
    url: jdbc:h2:./data/db
    driverClassName: org.h2.Driver
    username: eva
    password: 123456